apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: exai
data:
  # Cette valeur (encod√©e en base64) remplacera uniquement
  # la valeur de oauth-redirect-url dans le secret de base.
  oauth-redirect-url: REPLACE_WITH_OAUTH_REDIRECT_URL_PROD
